language: julia
sudo: false
os:
  - osx
  - linux
julia:
  - 0.4
  - 0.5
  # - latest  # Not working yet.
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("BayesianOptimization";  coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BayesianOptimization")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'cd(Pkg.dir("BayesianOptimization")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
